from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

from app.api.deps import get_current_user
from app.models.user import User
from app.services.llm import generate_chat_response, generate_chat_stream

router = APIRouter(prefix="/chat", tags=["chat"])


class ChatMessage(BaseModel):
    role: str = Field(
        ..., description="Role of the message author: 'user' or 'assistant'"
    )
    content: str = Field(..., description="The content of the message")


class ChatRequest(BaseModel):
    model: str = Field(
        ...,
        description="The LLM model name to run (e.g. 'gemini-2.5-flash', 'qwen2.5-coder:7b')",
    )
    messages: list[ChatMessage] = Field(..., description="The conversation history")
    system_instruction: str | None = Field(
        default=None, description="Optional system instructions or prompt guidelines"
    )
    temperature: float = Field(
        default=0.7, ge=0.0, le=2.0, description="Sampling temperature"
    )


class ChatResponse(BaseModel):
    response: str = Field(..., description="The response generated by the LLM")


@router.post("/", response_model=ChatResponse)
async def chat_with_llm(
    request: ChatRequest, current_user: Annotated[User, Depends(get_current_user)]
):
    """
    Exposes direct access to Gemini or local Ollama models.
    Requires user session cookie authentication.
    """
    try:
        # Convert Pydantic list of messages into list of dicts for the service
        msg_dicts = [
            {"role": msg.role, "content": msg.content} for msg in request.messages
        ]

        response_text = await generate_chat_response(
            model=request.model,
            messages=msg_dicts,
            system_instruction=request.system_instruction,
            temperature=request.temperature,
        )
        return ChatResponse(response=response_text)
    except Exception as e:  # noqa: BLE001
        # Raise HTTP 500 or detail error message
        raise HTTPException(
            status_code=500, detail=f"Failed to communicate with LLM: {e!s}"
        )


@router.post("/stream")
async def chat_stream_with_llm(
    request: ChatRequest, current_user: Annotated[User, Depends(get_current_user)]
):
    """
    Exposes a streaming response for Gemini or local Ollama.
    Requires user session cookie authentication.
    """
    msg_dicts = [{"role": msg.role, "content": msg.content} for msg in request.messages]

    async def event_generator():
        try:
            async for chunk in generate_chat_stream(
                model=request.model,
                messages=msg_dicts,
                system_instruction=request.system_instruction,
                temperature=request.temperature,
            ):
                yield chunk
        except Exception as e:  # noqa: BLE001
            yield f"\n[STREAM_ERROR: {e!s}]"

    return StreamingResponse(event_generator(), media_type="text/plain")
