"""add timestamps via TimestampModel

Revision ID: 393288337010
Revises: 93e934817757
Create Date: 2026-08-20 20:38:16.499517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '393288337010'
down_revision: Union[str, Sequence[str], None] = '93e934817757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'updated_at')
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'created_at')
    # ### end Alembic commands ###
