"""add user_id and status to projects

Revision ID: c38e3cbf09d2
Revises: 6f838019340d
Create Date: 2026-08-21 20:10:29.939650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c38e3cbf09d2'
down_revision: Union[str, Sequence[str], None] = '6f838019340d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'user_id')
    # ### end Alembic commands ###
